# # Make sure we’re using the latest Homebrew
# update

# # Upgrade any already-installed formulae
# upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew "coreutils"
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew "findutils"
# brew fish
brew "fish"

# brew wget with IRI support
brew "wget --enable-iri"

# brew other useful binaries
brew "git"
brew "imagemagick"
brew "tree"

brew "node"
brew "rbenv"
brew "ruby-build"
brew "rustup-init"
brew "elixir"
brew "postgresql"

# Remove outdated versions from the cellar
# cleanup
